config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index]

end

app/models/track.rb
class Track < ActiveRecord::Base
  include TracksHelper
  validates :title, :album_id, :track_number, presence: true
  validates :track_number, uniqueness: { scope: [:album_id, :track_number] }

  belongs_to :album
  has_one :band, through: :album
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :ensure_logged_in

  def show
    @track = Track.includes(:band, :album).find(params[:id])
    render :show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new
    @track.album_id = @album.id
    @albums = @album.band.albums
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      flash[:success] = ["#{@track.band.name} has written '#{@track.title}'!"]
      redirect_to track_url(@track.id)
    else
      flash[:errors] = ["Oops, something went wrong:"]
      flash[:errors].concat @track.errors.full_messages
      redirect_to new_album_track_url(@track.album_id)
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = @track.band.albums
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    @album = @track.album # same hack as in albums#update

    if @track.update_attributes(track_params)
      flash[:success] = ["'#{@track.title}' was successfully edited!"]
      redirect_to track_url(@track.id)
    else
      flash[:errors] = ["Oops. Something went wrong:"]
      flash[:errors].concat @track.errors.full_messages
      redirect_to edit_track_url(@track.id)
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy!
    flash[:success] = ["'#{@track.title}' didn't make it past QA."]
    redirect_to album_url(@track.album_id)
  end

  private
  def track_params
    params.require(:track)
    .permit(:title, :track_number, :bonus?, :album_id, :lyrics)
  end

  def ensure_logged_in
    unless logged_in?
      flash[:errors] = ["Please login before doing that."]
      redirect_to new_session_url
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    lyrics_ary = lyrics.split("\r\n")
    lyrics_ary.map! { |line| line = "♫ " + line }.join("\r\n")
  end
end

app/views/tracks/edit.html.erb
<h1>Edit "<%= @track.title %>"</h1>
<h5><i><%= link_to "back to album", album_url(@track.album_id) %></i></h5>

<form action='<%= track_url(@track.id) %>' method="POST">
  <input type='hidden' name='_method' value="PATCH">
  <%= render partial: 'shared/auth' %>

  <label for='track_title'>Title:</label>
  <input type='text' name='track[title]' id='track_title'
         value='<%= @track.title %>'>
  <br>

  <label for='track_track_number'>Track #</label>
  <input type='number' min=1 value='<%= @track.track_number %>'
         name='track[track_number]' id='track_track_number'>
  <br>

  Bonus track?
  <label for='bonus_track_true'>yes</label>
  <input type='radio'
         name='track[bonus?]'
         value=true
         id='bonus_track_true'
         <%= @track.bonus? ? "checked" : "" %>>

  <label for='bonus_track_false'>no</label>
  <input type='radio'
         name='track[bonus?]'
         value=false
         id='bonus_track_false'
         <%= @track.bonus? ? "" : "checked" %>>
  <br>

  <label for='track_album_id'>Album for this track:</label>
  <select name='track[album_id]' id='track_album_id'>
    <% @albums.each do |album| %>
      <option <%= @track.album_id == album.id ? "selected" : "" %>
       value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select><br>

  <label for 'track_lyrics'>Enter your wonderful new lyrics below:<br></label>
  <textarea name='track[lyrics]'><%= @track.lyrics %></textarea>
  <br><br>

  <input type='submit' value='Revise your artistic vision'>
</form>

app/views/tracks/new.html.erb
<h1>New track from <%= @album.band.name %></h1>

<form action='<%= tracks_url %>' method="POST">
  <%= render partial: 'shared/auth' %>

  <label for='track_title'>Title:</label>
  <input type='text' name='track[title]' id='track_title'>
  <br>

  <label for='track_track_number'>Track #</label>
  <input type='number' min=1
         name='track[track_number]' id='track_track_number'>
  <br>

  Bonus track?
  <label for='bonus_track_true'>yes</label>
  <input type='radio'
         name='track[bonus?]'
         value=true
         id='bonus_track_true'>

  <label for='bonus_track_false'>no</label>
  <input type='radio'
         name='track[bonus?]'
         value=false
         id='bonus_track_false'>
  <br>

  <label for='track_album_id'>Album for this track:</label>
  <select name='track[album_id]' id='track_album_id'>
    <% @albums.each do |album| %>
      <option <%= @track.album_id == album.id ? "selected" : "" %>
       value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select><br>

  <label for 'track_lyrics'>Enter your award-winning lyrics below:<br></label>
  <textarea name='track[lyrics]'></textarea>
  <br><br>

  <input type='submit' value='Make the music happen'>
</form>

app/views/tracks/show.html.erb
<h2><%= @track.title %></h2>
<h3>track <%= @track.track_number %> on '<%= @track.album.title %>' by <%= @track.band.name %></h3>
<h5>
  <i><%= link_to "back to album", album_url(@track.album_id) %></i> |
  <i><%= link_to "edit this track", edit_track_url(@track.id) %></i> |
  <i><%= link_to "destroy this track", track_url(@track.id), method: :delete,
         data: {
         confirm: "Leave '#{@track.title}' on the cutting room floor?" }
     %></i>
</h5>

<h4>Lyrics:</h4>
<p>
  <% unless @track.lyrics.empty? %>
    <pre><%= @track.ugly_lyrics(@track.lyrics) %></pre>
  <% else %>
    <i>-instrumental-</i>
  <% end %>
</p>