config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index]

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token,
            presence: true, uniqueness: true

  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(creds)
    usr = User.find_by_email(creds[:email])
    usr.is_password?(creds[:password]) ? usr : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.update(session_token: SecureRandom.urlsafe_base64)
    self.session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      flash[:success] = ["Welcome to MusicApp, #{@user.email}!"]
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = ["Sorry, something went wrong."]
      flash[:errors].concat @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = ["#{@user.email} has been ruthlessly destroyed."]
    redirect_to root_url
  end

  def edit
    fail
  end

  def update
    fail
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>It's everybody!</h1>

<% @users.each do |user| %>
  <%= link_to "#{user.email}", user_url(user.id) %>
<% end %>

app/views/users/new.html.erb
<h1>Create a new user</h1>

<form action='<%= users_url %>' method='POST'>
  <%= render 'shared/auth' %>

  <label for='user_email'>Email:</label>
  <input type='text' name='user[email]' id='user_email'>
  <br><br>

  <label for="user_password">Password:</label>
  <input type='password' name='user[password]' id='user_password'>
  <br>

  <input type='submit' value='Click to sign up!'>
</form>

app/views/users/show.html.erb
<h1><%= @user.email %>'s show page</h1>

<br>
<%= link_to "Back to home", root_url %> |
<%= link_to "Edit this user", edit_user_url(@user.id) %> |
<%= link_to "Delete this user", user_url,
    method: :delete, data: {
      confirm: "Are you sure you want to delete #{@user.email}?" } %>