config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index]

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def show
    @album = Album.includes(:band, :tracks).find(params[:id])
    render :show
  end

  def new
    @bands = Band.all
    @album = Album.new
    @album.band_id = params[:band_id]
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:success] = ["#{@album.band.name} has published '#{@album.title}'!"]
      redirect_to band_url(@album.band_id)
    else
      flash.now[:errors] = ["Oops, something went wrong:"]
      flash[:errors].concat @album.errors.full_messages
      redirect_to bands_url
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    @bands = Band.all # hacky thing to fix missing @bands on redirect
    old_name = @album.title

    if @album.update_attributes(album_params)
      flash[:success] = ["'#{old_name}' has been re-released as '#{@album.title}!'"]
      redirect_to album_url(@album.id)
    else
      flash[:errors] = ["Oops. Something went wrong:"]
      flash[:errors].concat @album.errors.full_messages
      redirect_to edit_album_url(@album.id)
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy!
    flash[:success] = ["All copies of #{@album.title} have been destroyed in a fit of artistic pique."]
    redirect_to band_url(@album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:title, :live?, :band_id)
  end

  def ensure_logged_in
    unless logged_in?
      flash[:errors] = ["Please login before doing that."]
      redirect_to new_session_url
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>Edit "<%= @album.title %>"</h1>
<h5><i><%= link_to "back to band", band_url(@album.band_id) %></i></h5>

<form action='<%= album_url(@album.id) %>' method='POST'>
  <input type='hidden' name="_method" value="PATCH">
  <%= render partial: 'shared/auth' %>

  <label for='album_band_id'>Recording band:</label>
  <select name='album[band_id]' id='album_band_id'>
    <% @bands.each do |band| %>
      <option <%= @album.band_id == band.id ? "selected" : "" %>
       value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select><br>

  Live album?
  <label for='album_live_true'>yes</label>
  <input type='radio'
         name='album[live?]'
         value=true
         id='album_live_true'
         <%= @album.live? ? "checked" : "" %>>

  <label for='album_live_false'>no</label>
  <input type='radio'
         name='album[live?]'
         value=false
         id='album_live_false'
         <%= @album.live? ? "" : "checked" %>>
  <br>

  <label for='album_title'>Record the album's new name: (make it better!)</label>
  <input type='text' name='album[title]'
         id='album_title' value='<%= @album.title %>'>
  <br>

  <input type='submit' value='Re-release your album!'>
</form>

app/views/albums/new.html.erb
<h1>New Album</h1>
<h5><i><%= link_to "back to index", bands_url %></i></h5>

<form action='<%= albums_url %>' method='POST'>
  <%= render partial: 'shared/auth' %>

  <label for='album_band_id'>Recording band:</label>
  <select name='album[band_id]' id='album_band_id'>
    <% @bands.each do |band| %>
      <option value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select><br>

  Live album?
  <label for='album_live_true'>yes</label>
  <input type='radio' name='album[live?]' value=true id='album_live_true'>
  <label for='album_live_false'>no</label>
  <input type='radio' name='album[live?]' value=false id='album_live_false'>
  <br>

  <label for='album_title'>Record your new album's title: (make it great!)</label>
  <input type='text' name='album[title]' id='album_title' value="<%= @album.title %>">
  <br>

  <input type='submit' value='Release your new album!'>
</form>

app/views/albums/show.html.erb
<h2><%= @album.title %></h2>
<h3>an album by <%= @album.band.name %></h3>
<h5>
  <i><%= link_to "back to band", band_url(@album.band_id) %></i> |
  <i><%= link_to "edit this album", edit_album_url(@album.id) %></i> |
  <i><%= link_to "create a new track", new_album_track_url(@album.id) %></i> |
  <i><%= link_to "destroy this album", album_url(@album.id), method: :delete,
         data: {
         confirm:
        "Consign '#{@album.title}' (and all its tracks) to the bargain bin?"
               }
     %></i>
</h5>

<% @album.tracks.sort_by { |t| t.track_number }.each do |track| %>
  <p>
    <%= track.track_number %>. <%= link_to "#{track.title}", track_url(track.id) %>
  </p>
<% end %>