config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index]

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  has_many :songs, through: :albums, source: :tracks
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in, except: :index

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      flash[:success] = ["#{@band.name} will make it big someday! Probably."]
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = ["Oops. Something went wrong:"]
      flash[:errors].concat @band.errors.full_messages
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy!
    flash[:success] = ["#{@band.name} has broken up."]
    redirect_to bands_url
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    old_name = @band.name

    if @band.update_attributes(band_params)
      flash[:success] = ["#{old_name} has been renamed to #{@band.name}."]
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = "Oops. Something went wrong:"
      flash[:errors].concat @band.errors.full_messages
      render :edit
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

  def ensure_logged_in
    unless logged_in?
      flash[:errors] = ["Please login before doing that."]
      redirect_to new_session_url
    end
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band.html.erb
<li>
    <h3><%= link_to "#{band.name}", band_url(band.id) %></h3>
</li>

app/views/bands/edit.html.erb
<h1>Edit details for <%= @band.name %></h1>
<i><h5><%= link_to "(back to index)", bands_url %></h5></i>

<form action='<%= band_url(@band.id) %>' method='POST'>
  <%= render partial: 'shared/auth' %>
  <input type='hidden' name='_method' value='PATCH'>

  <label for='band_name'>Enter <%= @band.name %>'s new name: (make it better!)</label>
  <input type='text' name='band[name]' id='band_name'>
  <br>

  <input type='submit' value='Continue the rocking'>
</form>

app/views/bands/index.html.erb
<h1>Bands Index</h1>
<h5>
  <i>
    <%= link_to "create a new band", new_band_url %>
  </i>
</h5>

<ul>
  <%= render @bands %>
</ul>

app/views/bands/new.html.erb
<h1>Create a new band!</h1>
<i><h5><%= link_to "(back to index)", bands_url %></h5></i>

<form action='<%= bands_url %>' method='POST'>
  <%= render partial: 'shared/auth' %>

  <label for='band_name'>Enter your new band's name: (make it good!)</label>
  <input type='text' name='band[name]' id='band_name'>
  <br>

  <input type='submit' value='Begin the rocking'>
</form>

app/views/bands/show.html.erb
<h1><%= "#{@band.name}" %></h1>
<h5>
  <i><%= link_to "back to index", bands_url %></i> |
  <i><%= link_to "edit this band", edit_band_url(@band.id) %></i> |
  <i><%= link_to "create a new album", new_band_album_url(@band.id) %></i>
   |
  <i><%= link_to "destroy this band", band_url(@band.id), method: :delete,
         data: {
         confirm:
        "Consign #{@band.name} (and all their works) to the dustbin of history?"
               }
     %>
  </i>
</h5>

<ul>
  <% @band.albums.each do |album| %>
    <li>
      <%= link_to "#{album.title}", album_url(album.id) %>
    </li>
  <% end %>
</ul>